version: "3.9"
services:
  db:
    image: postgres:15.4
    ports:
      - "5432:5432"
    restart: always
    profiles:
      - dev
      - local
    environment:
      POSTGRES_USER: open-erp
      POSTGRES_DB: open-erp
      POSTGRES_PASSWORD: open-erp-testing
  open-erp-accounting:
    depends_on:
      - db
    image: open-erp-accounting:latest
    build:
      context: .
    ports:
      - "8080:8080"
    profiles:
      - local
