name: Java & Gradle CI

on: [ push ]

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run the Gradle package task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
